export default location => {
  const locationDisplay =
    location === "nwCalgary"
      ? "NW Calgary"
      : location === "neCalgary"
      ? "NE Calgary"
      : location === "swCalgary"
      ? "SW Calgary"
      : location === "seCalgary"
      ? "SE Calgary"
      : location === "innerCityCalgary"
      ? "Inner City Calagry"
      : location === "airdrie"
      ? "Airdrie"
      : location === "chestermere"
      ? "Chestermere"
      : location === "cochrane"
      ? "Cochrane"
      : location === "okotoks"
      ? "Okotoks"
      : location === "crossfield"
      ? "Crossfield"
      : location === "canmore"
      ? "Canmore"
      : location === "banff"
      ? "Banff"
      : location === "siksikaMorley"
      ? "Siksika / Morley"
      : ""

  return locationDisplay
}
